name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    stpes:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Lint Tekshirish
        run: npm run lint